// ==================================================================
// FILE : Payment.cs
// LAYER: Domain (Entities)
// PATH : payment-service/FinVault.PaymentService.Domain/Entities/
//
// WHAT IS THIS?
// This is the CORE "thing" that Payment Service cares about.
// Every time a user pays a bill, we create one of these "Payment" objects.
//
// Think of it as a DIGITAL RECEIPT that we store in our own database.
// It stores:
// - Who paid (UserId)
// - Which card was used (CardId)
// - How much was paid (Amount)
// - Did it work? (Status: Success/Failed/Pending)
//
// Published by : payment-service (when processing a payment)
// Consumed by  : billing-service (via RabbitMQ to update bill status)
// ==================================================================

using System;

namespace FinVault.PaymentService.Domain.Entities;

public class Payment
{
    // Unique ID for this payment (Generated by our database)
    public Guid Id { get; set; }

    // Who is making the payment? 
    // We get this from the JWT token
    public Guid UserId { get; set; }

    // Which credit card are they paying?
    public Guid CardId { get; set; }

    // How much money are they paying?
    // We use "decimal" for money because it's super precise!
    public decimal Amount { get; set; }

    // Currency (e.g., INR, USD)
    public string Currency { get; set; } = "INR";

    // Current status of the payment (Pending, Success, Failed)
    // We start as "Pending" and change it once the "bank" says OK
    public string Status { get; set; }

    // When did they click the "Pay" button?
    public DateTime TransactionDate { get; set; }

    // Tracking ID from the External Bank / Payment Gateway
    // Helps us if we need to call the bank for support
    public string? ExternalTransactionId { get; set; }

    // A secret code from the bank saying "Yes, this is valid"
    public string? AuthorizationCode { get; set; }

    // Why did it fail? (e.g., "Insufficient funds", "Wrong OTP")
    public string? FailureReason { get; set; }
}
